DataBase impl
kinjalik/sqr-project pull request #5
Opened 2024-04-20 16:47 UTC by Markuu-s

2024-04-20 17:02 UTC, adarika commented on src/fastapi_app/app/db_client.py
> +        self.Session = sessionmaker(bind=self.engine)
с маленькой букавы)))

2024-04-20 17:02 UTC, adarika commented on src/fastapi_app/app/db_client.py
> +        self.Session = sessionmaker(bind=self.engine)
и лучше типа `make_session`

2024-04-20 17:03 UTC, adarika commented on src/fastapi_app/app/db_client.py
> +    email = Column(String, primary_key=True)
давай как в таске первичный ключ

2024-04-20 17:56 UTC, kinjalik approved these changes
lgtm

2024-04-20 19:22 UTC, Elestrias requested changes
make format сделай 
щас конфликтами порастем

btw ты как вообще вмержил ? за no-verify будешь пояснять!!!!

2024-04-25 15:52 UTC, Elestrias approved these changes

2024-04-25 17:16 UTC, merged